travis:
  secure:
    BINSTAR_TOKEN: kOU1N3cCjafKeXolgLdYyWD1q1AGiM0Lfmz0dGTOIwHDWWysKyv0L/GzOrDhJL9995qjYjS3OCDbTMh6+DE8LBXbDsPznxVhNWGGEUOsiNuC6ZJ5Nm6kxm2gvScL6jfjGkPWgFuo6+nTrOkKt3Z2B1xS/KIhJ5vBKKhZZjGUY6adtU+7ApQEcd3I2B+SNtEcU8+/GRfZvUNuPATYpTyve9Loa+UEUa6EObKgRBpXhEBFOKi0rAgXRmjjJIhtuhPL0WPagoqvzc7Dk+okUu4P/ebjGB9AXGN18VwxPjLgwa2SGt7b376AebSBpBmkOIMFig5l+5pEqvofh26n577lahcwdF6nfuzAz3uKP5l7j+h8rUs8s5+nWsWONJI5/3qiEa+nXmXIvxwAGLa2U5NtyD+qQIPRYi0Vvjkl/dAdpZ/Mwcm4aFmIBNVpup15sbcS8J1/y/LxcBfn3V5strKUYNUAU8vr0sDAy9kJP+5bTJK+tBPGopgY0lSILhqU2zWzhwYVGgSbJRd4ASziWPJ50MTM1iX+p5ghHF/p7SEMSlPkylwUecOvzt7Ni2ZWNpmn1u846hM39nRKJzGDq5TdoKD58u7GCdk6VsMNCK6OjbzuAc6to6ON1NrNXJgYvFrZRin6vPtGgjCjeUlZJJYNGppZLId8fawHosYHhtikIsY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
