travis:
  secure:
    BINSTAR_TOKEN: ZfeOpT6r+BYtd91031Na5Zs7AXfNl8/UGvPo+UpPmZ7CyljS8tFffWT/mYslS2Har3tT+EEttnLqqznn+hS2F8wAnMrw8VTbgb/VeesKCf0qApfo0u/Q6EPCApFLweW8H5SmtJMn+x+GOcKxyDz0jgrAwjIsZZyKiJ9C4vHzzlqnXXXcpQisBPft9fqU8Rhlln7wQIl9cWIfmgPqtK0U0Cogno00BllQbhLwXnhQu1lsbO1KIeIictceQTCByp6JX6f8t6PgQhyKPvQcWR3PM4uGbwKMlyvjkWOYoeZygVSR2605mrRO3Ad2D7WJw6Hs0cb2qNnBjqVTpPNlPucRdOdAO2VSailRAMDQ2uEcn1NvPXOu0RB+wRzL2VIYQQw2iPfLVT3Dc5oipE/5/eirS/WxtzTYxG8cWON9UEtwSQNBaTqqeHsBJpHn20vuFo0qNaH0bls5m9tZSCI2o/cwoJeOlsWsoFBQ1JTGqc/NzG3GtGt0So/uSQpMAkcJHJYJuYefWptz+pPVuJZrT9G6LHEntrzPzrWrcD5IUTSwr1b3Mo5M3muqv0djETpQZLaZ/RFVCHTLw7WzwgSwIB0xNxcY1ecQk89d7zP1thAqK5LqJvOBkPtGxddyrhLppsqKljK5LHepMDOL7ONX0rMwT7FGU90V6DnVj+mYcoR9Ro8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
